api_list:
    path: /{entityName}
    defaults:
        _controller: App\Controller\ApiController::list
        _format: json
    requirements:
       entityName: '[a-z_]+'
    methods: ['GET']

api_get:
    path: /{entityName}/{id}
    defaults:
        _controller: App\Controller\ApiController::getOne
        _format: json
    requirements:
        entityName: 'products'
        id: '\d+'
    methods:  ['GET']